try except with pathlib and pathlib2
CINPLA/exdir pull request #77
Opened 2019-04-24 11:17 UTC by lepmik

2019-04-24 11:19 UTC, lepmik commented
https://github.com/CINPLA/exdir/issues/74

2019-04-24 14:47 UTC, dragly commented on exdir/core/exdir_file.py
> +    try:
No need to wrap the second attempt in a try-block

2019-04-24 14:47 UTC, dragly commented on exdir/core/exdir_file.py
> +    except ImportError:
You can remove this as well (but if you don't, it is missing an `as e`).

2019-04-24 14:48 UTC, dragly commented on exdir/core/exdir_object.py
> +    try:
Ditto

2019-04-24 14:48 UTC, dragly commented on exdir/core/group.py
> +    try:
Ditto

2019-04-24 14:49 UTC, dragly requested changes

2019-04-24 14:49 UTC, dragly commented on exdir/core/validation.py
> +    try:
Ditto

2019-04-24 14:49 UTC, dragly commented on exdir/plugins/git_lfs.py
> +    try:
Ditto

2019-04-24 14:49 UTC, dragly commented on exdir/utils/display.py
> +    try:
Ditto

2019-04-24 14:49 UTC, dragly commented on exdir/utils/path.py
> +    try:
Ditto

2019-04-24 14:49 UTC, dragly commented on tests/conftest.py
> +    try:
Ditto

2019-04-24 14:49 UTC, dragly commented on tests/test_file.py
> +    try:
Ditto, and, I guess you get the point. The following do not need the try either.

2019-04-24 15:19 UTC, lepmik commented
The reason I put the second try except is to raise the error from the first try except . That is, if you don't have either pathlib or pathlib2 you will get an error saying you don't have pathlib, not pathlib2 as your suggestion would result in.

2019-04-25 08:41 UTC, lepmik commented
@dragly do you concur?

2019-05-06 15:48 UTC, dragly approved these changes
Sorry, did not see your reply before now. Yes, then I agree. Nice trick!

2019-05-06 16:08 UTC, merged